export const SET_DATA_REQUEST = "SET_DATA_REQUEST"
export const SET_DATA_SUCCESS = "SET_DATA_SUCCESS"
export const SET_DATA_FAIL = "SET_DATA_FAIL"
export const SET_DATA_RESET = "SET_DATA_RESET"

export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAIL = "GET_DATA_FAIL"

export const SET_COLUMNS = "SET_COLUMNS"
export const SET_FILE_NAME = "SET_FILE_NAME"
export const CLEAR_DATA = "CLEAR_DATA"
