export const LOAD_TABLE_REQUEST = 'LOAD_TABLE_REQUEST'
export const LOAD_TABLE_SUCCESS = 'LOAD_TABLE_SUCCESS'
export const LOAD_TABLE_FAIL = 'LOAD_TABLE_FAIL'

export const LOAD_TABLE_REMOVE_REQUEST = 'LOAD_TABLE_REMOVE_REQUEST'
export const LOAD_TABLE_REMOVE_SUCCESS = 'LOAD_TABLE_REMOVE_SUCCESS'
export const LOAD_TABLE_REMOVE_FAIL = 'LOAD_TABLE_REMOVE_FAIL'
export const LOAD_TABLE_REMOVE_RESET = 'LOAD_TABLE_REMOVE_RESET'

// export const CURRENT_TABLE_DATA_REQUEST = 'CURRENT_TABLE_DATA_REQUEST'
// export const CURRENT_TABLE_DATA_SUCCESS = 'CURRENT_TABLE_DATA_SUCCESS'
// export const CURRENT_TABLE_DATA_FAIL = 'CURRENT_TABLE_DATA_FAIL'
// export const CURRENT_TABLE_DATA_RESET = 'CURRENT_TABLE_DATA_RESET'